### ISSUE TITLE
CMake build system

### ISSUE THREAD

**Issue by mkstoyanov** [ORNL-Fusion/KORC#1]
I added a cmake build system to KORC, this is a start and we can build from here.

* added CMakeLists.txt, the current code sits in a sub-directory, we can add new sub-directories as we convert the code to C++
* added FindPspline module, the pspline folder should be specified with either CMAKE_PREFIX_PATH or Pspline_ROOT_DIR
* added option for double vs single precision, KORC_ENABLE_DOUBLE_PRECISION is ON by default

@lcarbajal, check the code, we can merge into master, if you are happy with the changes.

**Comment by lcarbajal** [comment]
@mkstoyanov the build systems works great, thanks. I just made some minor changes so this works on Mac OS with GNU compilers, too. Also, I've included the option for having a local installation of HDF5, which is the case in some small clusters we've used before.
Please go ahead and give it a final test on your system(s) and if this works fine with my modifications, I'll merge it with the master.
Cheers.
