### ISSUE TITLE
ExCL workflow hangs looking for running until an ssh connection is made

### ISSUE THREAD

**Issue by mbeidler3** [ORNL-Fusion/KORC#47]

**Comment by idigs** [comment]
A workaround: open a tmux session on milan0 and leave it running after exit

**Comment by idigs** [comment]
Resolved: https://docs.excl.ornl.gov/quick-start-guides/github-ci#enable-linger-for-your-user

**Comment by idigs** [comment]
Resolved: https://docs.excl.ornl.gov/quick-start-guides/github-ci#enable-linger-for-your-user
