### ISSUE TITLE
investigate broken builds

### ISSUE THREAD

**Issue by idigs** [ORNL-Fusion/KORC#69]
It seems that an upstream dependency in our current spack cache is no longer working for new builds.  Point in case, when re-running any of the agate workflows they produce an error when running ctest

**Comment by mbeidler3** [comment]
PR #73 is addressing this. There were several Floating Point Exceptions that were found with --ffpe-trap=overflow. These have been fixed in the source code.

**Comment by mbeidler3** [comment]
close
